---
name: template of deploy aws lambda

on:
  workflow_call:
    inputs:
      LAMBDA_FUNCTION_NAME:
        type: string
        required: true
      WORKING_DIR:
        type: string
        required: true
      AWS_REGION:
        type: string
        required: true
      PYTHON_PACKAGE_FOLDER:
        type: string
        default: packages
      LAMBDA_ZIP_FILE:
        type: string
        default: lambda_function_payload.zip
    secrets:
      OIDC_AWS_ROLE_ARN:
        required: true

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIR }}
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.OIDC_AWS_ROLE_ARN }}
          aws-region: ${{ inputs.AWS_REGION }}

      # NOTE: Read python version from .python-version in the workging directory.
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - run: uname -m

      - name: Create package folder
        run: mkdir ${{ inputs.PYTHON_PACKAGE_FOLDER }}

      - name: Create venv and install python packages
        run: | 
          python -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt

      - name: Zip python packages
        run: zip -r ${{ inputs.LAMBDA_ZIP_FILE }} .venv/lib/python3.9/site-packages && rm -rf .venv

      - name: Zip lambda function
        run: zip -g ${{ inputs.LAMBDA_ZIP_FILE }} $(find . -type f -name "*.py")

      - name: Update lambda function
        run: |
          aws lambda update-function-code --function-name ${{ inputs.LAMBDA_FUNCTION_NAME }} --zip-file fileb://${{ inputs.LAMBDA_ZIP_FILE }}
          