---
name: deploy aws lambda of bigquery transfer of snapshot

on:
  push:
    branches:
      - main
    paths:
      - rds-snapshot-exporter/aws/lambda/transfer_to_bigquery/**/*

jobs:
  call_workflow:
    uses: ./.github/workflows/_deploy_lambda.yml
    with:
      LAMBDA_FUNCTION_NAME: test-transfer-to-bigquery
      WORKING_DIR: rds-snapshot-exporter/aws/lambda/transfer_to_bigquery
      AWS_REGION: ap-northeast-1
    secrets:
      OIDC_AWS_ROLE_ARN: ${{ secrets.OIDC_AWS_ROLE_ARN }}